import type { Challenge, ChallengeTier, ChallengeType } from '@/core/domain/types';

// Desafios oficiais da Liga X (apresentados pelo Haroldo).
// Para adicionar um desafio novo basta um item nesta lista — a tela se vira.
// `npm run validate` confere se toda posição e toda solução são válidas.

export const CHALLENGE_TYPE_LABEL: Record<ChallengeType, string> = {
  'mate-1': 'Mate em 1',
  'mate-2': 'Mate em 2',
  'mate-3': 'Mate em 3',
  'best-move': 'Melhor jogada',
  'win-material': 'Ganhe material',
  fork: 'Garfo',
  pin: 'Cravada',
  skewer: 'Espeto',
  endgame: 'Final',
  historic: 'Posição histórica',
  timed: 'Contra o relógio',
  daily: 'Desafio do dia',
};

export const CHALLENGE_TIERS: ChallengeTier[] = [
  { tier: 1, title: 'Aquecimento', description: 'Um lance e acabou. Ache o mate.', unlockAfter: 0 },
  { tier: 2, title: 'Golpes táticos', description: 'Garfo, cravada, espeto. Ganhe material.', unlockAfter: 3 },
  { tier: 3, title: 'Combinações', description: 'Dois lances à frente.', unlockAfter: 2 },
  { tier: 4, title: 'Desafio do Haroldo', description: 'Só pra quem chegou até aqui.', unlockAfter: 3 },
];

export const CHALLENGES: Challenge[] = [
  // ── Aquecimento ──
  {
    id: 'corredor',
    type: 'mate-1',
    title: 'Corredor',
    prompt: 'Brancas jogam. Mate em 1.',
    fen: '6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ['Re8#'],
    mateIn: 1,
    tier: 1,
    xp: 15,
    hint: 'Os peões do rei preto viraram uma parede. Contra ele.',
    successText: 'Mate do corredor. Rei sem saída na última fileira.',
    failText: 'Quase. Observe a posição do rei adversário.',
    source: 'liga',
  },
  {
    id: 'pastor',
    type: 'mate-1',
    title: 'Mate do Pastor',
    prompt: 'Brancas jogam. Mate em 1.',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    solution: ['Qxf7#'],
    mateIn: 1,
    tier: 1,
    xp: 15,
    hint: 'Dama e bispo estão olhando pra mesma casa.',
    successText: 'O famoso Mate do Pastor. Agora você nunca mais cai nele.',
    failText: 'Não é esse. Qual casa só o rei preto defende?',
    source: 'liga',
  },
  {
    id: 'dama-e-rei',
    type: 'mate-1',
    title: 'Dama e rei',
    prompt: 'Brancas jogam. Mate em 1.',
    fen: '7k/5Q2/6K1/8/8/8/8/8 w - - 0 1',
    solution: ['Qg7#'],
    mateIn: 1,
    tier: 1,
    xp: 15,
    hint: 'Seu rei já tira as casas de fuga. A dama só precisa encostar.',
    successText: 'Rei e dama trabalhando juntos. É assim que se fecha uma partida.',
    failText: 'Cuidado: se o rei preto ficar sem lance e sem xeque, é empate.',
    source: 'liga',
  },
  {
    id: 'sufocado',
    type: 'mate-1',
    title: 'Sem ar',
    prompt: 'Brancas jogam. Mate em 1.',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: ['Nf7#'],
    mateIn: 1,
    tier: 1,
    xp: 15,
    hint: 'O rei preto está cercado pelas próprias peças.',
    successText: 'Mate sufocado. As peças dele mesmo fecharam a porta.',
    failText: 'Não. Só uma peça sua consegue dar xeque aqui.',
    source: 'liga',
  },
  {
    id: 'louco',
    type: 'mate-1',
    title: 'Mate do Louco',
    prompt: 'Pretas jogam. Mate em 1.',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2',
    solution: ['Qh4#'],
    mateIn: 1,
    tier: 1,
    xp: 15,
    hint: 'As brancas abriram a diagonal do próprio rei.',
    successText: 'O mate mais rápido do xadrez. Dois lances e fim.',
    failText: 'Olhe a diagonal que vai até o rei branco.',
    source: 'liga',
  },

  // ── Golpes táticos ──
  {
    id: 'garfo-real',
    type: 'fork',
    title: 'Dois de uma vez',
    prompt: 'Brancas jogam e ganham a dama.',
    fen: '4k3/8/q7/3N4/8/8/8/4K3 w - - 0 1',
    solution: ['Nc7+', 'Kd7', 'Nxa6'],
    tier: 2,
    xp: 25,
    hint: 'Existe uma casa de onde o cavalo ataca rei e dama juntos.',
    successText: 'Boa! Garfo de cavalo. O rei foge e a dama fica.',
    failText: 'Assim a dama escapa. Procure um lance com xeque.',
    source: 'liga',
  },
  {
    id: 'cravada-fatal',
    type: 'pin',
    title: 'Presa na diagonal',
    prompt: 'Brancas jogam e ganham a dama.',
    fen: '6k1/6pp/8/3q4/8/1P6/6PP/5BK1 w - - 0 1',
    solution: ['Bc4', 'Qxc4', 'bxc4'],
    tier: 2,
    xp: 25,
    hint: 'Dama e rei pretos estão na mesma diagonal.',
    successText: 'Cravada. A dama não podia sair da frente do rei.',
    failText: 'Não é isso. O que a dama preta está escondendo atrás dela?',
    source: 'liga',
  },
  {
    id: 'espeto',
    type: 'skewer',
    title: 'Espeto',
    prompt: 'Brancas jogam e ganham a dama.',
    fen: '3q4/8/8/3k4/8/8/8/R3K3 w - - 0 1',
    solution: ['Rd1+', 'Ke6', 'Rxd8'],
    tier: 2,
    xp: 25,
    hint: 'Rei e dama na mesma coluna. O rei vai ter que sair da frente.',
    successText: 'Espeto. O rei sai e a dama fica na linha de tiro.',
    failText: 'Quase. Dê um xeque que deixe a dama exposta.',
    source: 'liga',
  },

  // ── Combinações ──
  {
    id: 'escada',
    type: 'mate-2',
    title: 'A escada',
    prompt: 'Brancas jogam. Mate em 2.',
    fen: '7k/8/8/8/8/8/R7/1R4K1 w - - 0 1',
    solution: ['Ra7', 'Kg8', 'Rb8#'],
    mateIn: 2,
    tier: 3,
    xp: 40,
    hint: 'Uma torre tranca a fileira, a outra dá o mate.',
    successText: 'Boa! Você encontrou a combinação. Duas torres, um degrau de cada vez.',
    failText: 'Xeque agora não resolve. Primeiro tire as casas do rei.',
    source: 'liga',
  },
  {
    id: 'rei-ajuda',
    type: 'mate-2',
    title: 'O rei também joga',
    prompt: 'Brancas jogam. Mate em 2.',
    fen: 'k7/8/2K5/8/8/8/8/6Q1 w - - 0 1',
    solution: ['Kb6', 'Kb8', 'Qg8#'],
    mateIn: 2,
    tier: 3,
    xp: 40,
    hint: 'Não precisa ser xeque. Aproxime e deixe só uma casa pro rei preto.',
    successText: 'Isso. No final, o rei é peça de ataque.',
    failText: 'Assim ele escapa, ou pior: fica afogado. Tente de novo.',
    source: 'liga',
  },
  {
    id: 'dama-por-mate',
    type: 'mate-2',
    title: 'Dama por mate',
    prompt: 'Brancas jogam. Mate em 2.',
    fen: '1Q3rk1/4pppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
    solution: ['Qxf8+', 'Kxf8', 'Rd8#'],
    mateIn: 2,
    tier: 3,
    xp: 40,
    hint: 'A torre preta é a única coisa que guarda a última fileira.',
    successText: 'Sacrificou a dama e deu mate. Agora ficou sério.',
    failText: 'Essa posição tem uma pegadinha. Vale entregar material?',
    source: 'liga',
  },
  {
    id: 'nem-sempre-dama',
    type: 'mate-2',
    title: 'Nem sempre dama',
    prompt: 'Brancas jogam. Mate em 2.',
    fen: '8/5P1k/5K2/8/8/8/8/8 w - - 0 1',
    solution: ['f8=R', 'Kh6', 'Rh8#'],
    mateIn: 2,
    tier: 3,
    xp: 40,
    hint: 'Se você promover a dama, o rei preto fica sem lance. E isso é empate.',
    successText: 'Promoveu a torre e evitou o afogamento. Pouca gente lembra disso.',
    failText: 'Calma. Pensa antes de mexer: depois do seu lance, o rei preto consegue jogar?',
    source: 'liga',
  },

  // ── Desafio do Haroldo ──
  {
    id: 'relampago',
    type: 'timed',
    title: 'Relâmpago',
    prompt: 'Brancas jogam. Mate em 1. Você tem 20 segundos.',
    fen: 'r4rk1/ppp2ppp/8/8/8/2Q5/1B3PPP/6K1 w - - 0 1',
    solution: ['Qxg7#'],
    mateIn: 1,
    tier: 4,
    xp: 40,
    timeLimitSec: 20,
    hint: 'Dama e bispo na mesma diagonal.',
    successText: 'Rápido e certo. É assim que eu gosto.',
    failText: 'O tempo corre. Olhe a diagonal grande.',
    source: 'liga',
  },
  {
    id: 'desafio-final',
    type: 'mate-3',
    title: 'O legado',
    prompt: 'Brancas jogam. Mate em 3. Esse desafio não vai ser fácil.',
    fen: '5rk1/5Npp/8/8/2Q5/8/8/6K1 w - - 0 1',
    solution: ['Nh6+', 'Kh8', 'Qg8+', 'Rxg8', 'Nf7#'],
    mateIn: 3,
    tier: 4,
    xp: 80,
    hint: 'Xeque duplo primeiro. Depois, a dama vale menos que o mate.',
    successText: 'Xeque duplo, sacrifício de dama e mate sufocado. Você realmente aprendeu.',
    failText: 'Não. Procure um lance em que duas peças dão xeque ao mesmo tempo.',
    source: 'liga',
  },
];

export function findChallenge(id: string): Challenge | undefined {
  return CHALLENGES.find((c) => c.id === id);
}
